# DATA INGESTION
**Sources** : \
Get sources from external folder
- google trends
- yahoo
- glassnode

**Goals** :
- Database creation
- Put data into the Raw folder

In [4]:
import pandas as pd
from datetime import date

## Sources

### Google Trends

In [37]:
gogole_df = pd.read_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/external/google/google_trends/btc_googletrends_2021_10_21.parquet.gzip')
gogole_df

            bitcoin  btc  cryptocurrency  isPartial
date
2014-08-31       55   16               1      False
2014-09-01       59   15               1      False
2014-09-02       50   13               1      False
2014-09-03       51   18               1      False
2014-09-04       48   18               1      False
...             ...  ...             ...        ...
2021-10-15        3    1               0      False
2021-10-16        2    0               0      False
2021-10-17        2    0               0      False
2021-10-18        2    0               0      False
2021-10-19      100   72              39      False

[2623 rows x 4 columns]

In [38]:
google_db = google_df.loc['2014-09-17':].copy()
google_db

            bitcoin  btc  cryptocurrency  isPartial
date
2014-09-17       44   15               1      False
2014-09-18       50   18               1      False
2014-09-19       56   19               0      False
2014-09-20       52   19               1      False
2014-09-21       59   17               1      False
...             ...  ...             ...        ...
2021-10-15        3    1               0      False
2021-10-16        2    0               0      False
2021-10-17        2    0               0      False
2021-10-18        2    0               0      False
2021-10-19      100   72              39      False

[2606 rows x 4 columns]

In [39]:
#google_db.to_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/raw/btc_googletrends_{}.parquet.gzip'.format(date.today().strftime("%Y_%m_%d")), compression='gzip')

### Yahoo

In [41]:
yahoo_df = pd.read_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/external/yahoo/daily/usd/all_yahoo_2021_10_21.parquet.gzip')
yahoo_df

             VET-USD                                              \
                Open      High       Low     Close        Volume
Date
1927-12-30       NaN       NaN       NaN       NaN           NaN
1928-01-03       NaN       NaN       NaN       NaN           NaN
1928-01-04       NaN       NaN       NaN       NaN           NaN
1928-01-05       NaN       NaN       NaN       NaN           NaN
1928-01-09       NaN       NaN       NaN       NaN           NaN
...              ...       ...       ...       ...           ...
2021-10-17  0.119825  0.127527  0.116873  0.122243  6.345386e+08
2021-10-18  0.122254  0.123747  0.116978  0.118551  4.218356e+08
2021-10-19  0.118551  0.119335  0.114771  0.116163  3.372777e+08
2021-10-20  0.116161  0.123003  0.115251  0.122075  4.134303e+08
2021-10-21  0.123163  0.135694  0.122209  0.132979  1.012209e+09

                 BTC-USD                                            \
                    Open          High           Low         Close
Date
1927-12-30           NaN           NaN           NaN           NaN
1928-01-03           NaN           NaN           NaN           NaN
1928-01-04           NaN           NaN           NaN           NaN
1928-01-05           NaN           NaN           NaN           NaN
1928-01-09           NaN           NaN           NaN           NaN
...                  ...           ...           ...           ...
2021-10-17  60887.652344  61645.523438  59164.468750  61553.617188
2021-10-18  61548.804688  62614.660156  60012.757812  62026.078125
2021-10-19  62043.164062  64434.535156  61622.933594  64261.992188
2021-10-20  64284.585938  66930.390625  63610.675781  65992.835938
2021-10-21  65919.140625  66561.132812  62535.437500  62775.523438

                          ...          ^DJI                              \
                  Volume  ...          Open          High           Low
Date                      ...
1927-12-30           NaN  ...           NaN           NaN           NaN
1928-01-03           NaN  ...           NaN           NaN           NaN
1928-01-04           NaN  ...           NaN           NaN           NaN
1928-01-05           NaN  ...           NaN           NaN           NaN
1928-01-09           NaN  ...           NaN           NaN           NaN
...                  ...  ...           ...           ...           ...
2021-10-17  2.903237e+10  ...           NaN           NaN           NaN
2021-10-18  3.805556e+10  ...  35221.019531  35327.570312  35035.941406
2021-10-19  4.047120e+10  ...  35325.371094  35462.679688  35290.121094
2021-10-20  4.078896e+10  ...  35475.160156  35669.691406  35465.710938
2021-10-21  4.688261e+10  ...  35520.320312  35612.359375  35442.531250

                                              ^IXIC                \
                   Close       Volume          Open          High
Date
1927-12-30           NaN          NaN           NaN           NaN
1928-01-03           NaN          NaN           NaN           NaN
1928-01-04           NaN          NaN           NaN           NaN
1928-01-05           NaN          NaN           NaN           NaN
1928-01-09           NaN          NaN           NaN           NaN
...                  ...          ...           ...           ...
2021-10-17           NaN          NaN           NaN           NaN
2021-10-18  35258.609375  312640000.0  14839.740234  15026.679688
2021-10-19  35457.308594  278510000.0  15073.129883  15137.849609
2021-10-20  35609.339844  265750000.0  15160.000000  15178.389648
2021-10-21  35603.078125  298390473.0  15104.799805  15222.254883


                     Low         Close        Volume
Date
1927-12-30           NaN           NaN           NaN
1928-01-03           NaN           NaN           NaN
1928-01-04           NaN           NaN           NaN
1928-01-05           NaN           NaN           NaN
1928-01-09           NaN           NaN           NaN
...                  ...           ...           ...
2021-10-17           NaN           NaN           NaN
2021-10-18  14833.280273  15021.809570  4.142540e+09
2021-10-19  15049.730469  15129.089844  4.443000e+09
2021-10-20  15071.150391  15121.679688  4.086590e+09
2021-10-21  15094.140625  15215.700195  4.309665e+09

[20621 rows x 161 columns]

In [42]:
yahoo_db = yahoo_df.loc['2014-09-17':].copy()
yahoo_db

             VET-USD                                              \
                Open      High       Low     Close        Volume
Date
2014-09-17       NaN       NaN       NaN       NaN           NaN
2014-09-18       NaN       NaN       NaN       NaN           NaN
2014-09-19       NaN       NaN       NaN       NaN           NaN
2014-09-20       NaN       NaN       NaN       NaN           NaN
2014-09-21       NaN       NaN       NaN       NaN           NaN
...              ...       ...       ...       ...           ...
2021-10-17  0.119825  0.127527  0.116873  0.122243  6.345386e+08
2021-10-18  0.122254  0.123747  0.116978  0.118551  4.218356e+08
2021-10-19  0.118551  0.119335  0.114771  0.116163  3.372777e+08
2021-10-20  0.116161  0.123003  0.115251  0.122075  4.134303e+08
2021-10-21  0.123163  0.135694  0.122209  0.132979  1.012209e+09

                 BTC-USD                                            \
                    Open          High           Low         Close
Date
2014-09-17    465.864014    468.174011    452.421997    457.334015
2014-09-18    456.859985    456.859985    413.104004    424.440002
2014-09-19    424.102997    427.834991    384.532013    394.795990
2014-09-20    394.673004    423.295990    389.882996    408.903992
2014-09-21    408.084991    412.425995    393.181000    398.821014
...                  ...           ...           ...           ...
2021-10-17  60887.652344  61645.523438  59164.468750  61553.617188
2021-10-18  61548.804688  62614.660156  60012.757812  62026.078125
2021-10-19  62043.164062  64434.535156  61622.933594  64261.992188
2021-10-20  64284.585938  66930.390625  63610.675781  65992.835938
2021-10-21  65919.140625  66561.132812  62535.437500  62775.523438

                          ...          ^DJI                              \
                  Volume  ...          Open          High           Low
Date                      ...
2014-09-17  2.105680e+07  ...  17131.009766  17221.109375  17089.009766
2014-09-18  3.448320e+07  ...  17163.730469  17275.369141  17163.730469
2014-09-19  3.791970e+07  ...  17267.210938  17350.640625  17257.460938
2014-09-20  3.686360e+07  ...           NaN           NaN           NaN
2014-09-21  2.658010e+07  ...           NaN           NaN           NaN
...                  ...  ...           ...           ...           ...
2021-10-17  2.903237e+10  ...           NaN           NaN           NaN
2021-10-18  3.805556e+10  ...  35221.019531  35327.570312  35035.941406
2021-10-19  4.047120e+10  ...  35325.371094  35462.679688  35290.121094
2021-10-20  4.078896e+10  ...  35475.160156  35669.691406  35465.710938
2021-10-21  4.688261e+10  ...  35520.320312  35612.359375  35442.531250

                                              ^IXIC                \
                   Close       Volume          Open          High
Date
2014-09-17  17156.849609   87810000.0   4553.959961   4582.399902
2014-09-18  17265.990234   85300000.0   4575.740234   4593.979980
2014-09-19  17279.740234  349620000.0   4606.129883   4610.569824
2014-09-20           NaN          NaN           NaN           NaN
2014-09-21           NaN          NaN           NaN           NaN
...                  ...          ...           ...           ...
2021-10-17           NaN          NaN           NaN           NaN
2021-10-18  35258.609375  312640000.0  14839.740234  15026.679688
2021-10-19  35457.308594  278510000.0  15073.129883  15137.849609
2021-10-20  35609.339844  265750000.0  15160.000000  15178.389648
2021-10-21  35603.078125  298390473.0  15104.799805  15222.254883


                     Low         Close        Volume
Date
2014-09-17   4539.359863   4562.189941  1.796710e+09
2014-09-18   4572.620117   4593.430176  1.774840e+09
2014-09-19   4563.439941   4579.790039  3.178490e+09
2014-09-20           NaN           NaN           NaN
2014-09-21           NaN           NaN           NaN
...                  ...           ...           ...
2021-10-17           NaN           NaN           NaN
2021-10-18  14833.280273  15021.809570  4.142540e+09
2021-10-19  15049.730469  15129.089844  4.443000e+09
2021-10-20  15071.150391  15121.679688  4.086590e+09
2021-10-21  15094.140625  15215.700195  4.309665e+09

[2592 rows x 161 columns]

In [43]:
#yahoo_db.to_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/raw/all_yahoo_{}.parquet.gzip'.format(date.today().strftime("%Y_%m_%d")), compression='gzip')

### Glassnode

In [82]:
from os import listdir

In [43]:
glass_files = [ 'adr_df_btc', 'fees_df', 'indicator_df1', 'indicator_df3', 'market_df', 'supply_df', 'transact_df']
glass_files

In [45]:
adr_df = pd.read_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/external/glassnode/btc/adr_df_btc_2021_10_24.parquet.gzip')

fees_df = pd.read_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/external/glassnode/btc/fees_df_2021_10_24.parquet.gzip')

indicator_df1 = pd.read_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/external/glassnode/btc/indicator_df1_2021_10_24.parquet.gzip')

indicator_df3 = pd.read_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/external/glassnode/btc/indicator_df3_2021_10_24.parquet.gzip')

market_df = pd.read_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/external/glassnode/btc/market_df_2021_10_24.parquet.gzip')

supply_df = pd.read_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/external/glassnode/btc/supply_df_2021_10_24.parquet.gzip')

transact_df = pd.read_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/external/glassnode/btc/transact_df_2021_10_24.parquet.gzip')

In [62]:
glassnode_db = adr_df.join(fees_df).join(indicator_df1).join(indicator_df3).join(market_df, rsuffix='_mkt').join(supply_df).join(transact_df,  rsuffix='_transact')
glassnode_db

,count,sending_count,receiving_count,active_count,new_non_zero_count,non_zero_count,min_point_zero_1_count,min_point_1_count,min_1_count,min_10_count,...,transfers_between_exchanges_count,transfers_volume_between_exchanges_sum,transfers_volume_to_exchanges_mean,transfers_volume_from_exchanges_mean,transfers_volume_exchanges_net,transfers_to_exchanges_count,transfers_from_exchanges_count,transfers_volume_to_exchanges_sum,transfers_volume_from_exchanges_sum,transfers_volume_within_exchanges_sum
t,,,,,,,,,,,,,,,,,,,,,
2009-01-03,1,0,0,0,1,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-04,1,0,0,0,0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-05,1,0,0,0,0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-06,1,0,0,0,0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2009-01-07,1,0,0,0,0,1.0,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-19,890556967,721691,743760,1077630,488426,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-20,891017464,594967,713145,975443,460497,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-21,891520431,760647,765433,1135695,502967,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-22,891969926,642110,693358,974151,449495,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-10-23,892350675,493467,597140,814845,380749,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [63]:
#glassnode_db.to_parquet('/home/giujorge/datalake/lab/Crypto/crypto/data/raw/all_glassnode_{}.parquet.gzip'.format(date.today().strftime("%Y_%m_%d")), compression='gzip')